src/routes/web.php
<?php

Route::group(['namespace' => 'Wellingtonsm\\Lockscreen\\Controllers', 'as' => 'lockscreen.'], function (){
	Route::get('lock', 'LockscreenController@lock')->name('lock');
	Route::post('unlock', 'LockscreenController@unlock')->name('unlock');
});

src/controllers/LockscreenController.php
<?php

namespace Wellingtonsm\Lockscreen\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Wellingtonsm\Lockscreen\Services\LockscreenService;
use Illuminate\Support\Facades\Auth;

class LockscreenController extends Controller
{
	protected $lockscreen_service;

	public function __construct(LockscreenService $lockscreen_service)
	{
		$this->lockscreen_service = $lockscreen_service;

		$this->middleware('web');
	}

	/**
	 * Lock session and display the lockscreen.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function lock()
	{
	    if(Auth::guest()) return redirect()->back();

		$lock = $this->lockscreen_service->lock();

		if($lock['status']) return view('lockscreen::index', compact('lock'));

		return redirect($lock['page']);
	}

	/**
	 * Try unlock the session by password.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function unlock(Request $request)
	{
		$result = $this->lockscreen_service->lockOrUnlock($request);

	    return redirect($result['page']);
	}
}

src/resources/views/index.blade.php
@extends('lockscreen::layouts.master')

@section('content')
    @include('lockscreen::themes.' . config('lockscreen.theme'))
@endsection

src/resources/views/layouts/master.blade.php
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    @include('lockscreen::styles.' . config('lockscreen.theme'))
</head>
<body class="flex-container">
<form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
    {{ csrf_field() }}
</form>
@yield('content')
<script>
    document.getElementById('lockscreen-logout').addEventListener('click', function (event) {
        event.preventDefault();
        document.getElementById('frm-logout').submit();
    });
</script>
</body>
</html>

src/resources/views/styles/adminlte.blade.php
<style>
    body {
        background-color: #eee;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        text-align: center;
    }

    .flex-container {
        padding: 20px;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -ms-flex-align: center;
        -webkit-align-items: center;
        -webkit-box-align: center;
        align-items: center;
    }

    .flex-container > * {
        margin: auto;
    }

    .box-lockscreen {
        min-width: 280px;
        max-width: 400px;
        height: auto;
        background-color: rgba(255, 255, 255, .9);
        border: 1px solid #d1d4d7;
        padding: 30px;
    }

    h2 {
        font-size: 16px;
        line-height: 16px;
        font-weight: 400;
    }

    p {
        margin-top: -8px;
        font-weight: 300;
    }

    .input-group {
        position: relative;
        display: flex;
        border-collapse: separate;
        margin-bottom: -10px;
        margin-top: 30px;
    }

    .input-group .form-control, .input-group-btn {
        display: table-cell;
    }

    .input-group .form-control {
        position: relative;
        z-index: 2;
        float: left;
        width: 100%;
        margin-bottom: 0;
        color: #3d3f42;
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
        border: 2px solid #333;
        border-right-width: 0px;
    }

    .form-control {
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
        -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
    }

    .input-group-btn:last-child > .btn, .input-group-btn:last-child > .btn-group {
        margin-left: -1px;
    }

    .input-group-btn > .btn {
        position: relative;
        margin-bottom: 25px;
        color: #333;
        border: 2px solid #333;
        background: transparent;
        text-shadow: none;
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
        font-weight: 600;
    }

    .btn {
        display: inline-block;
        padding: 5px 12px;
        margin-bottom: 0;
        font-size: 14px;
        font-weight: 400;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        -ms-touch-action: manipulation;
        touch-action: manipulation;
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        background-image: none;
        border: 1px solid transparent;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
    }

    a {
        display: block;
        font-weight: 300;
        font-size: 14px;
        color: #337ab7;
        text-decoration: none;
    }
</style>

src/resources/views/styles/bootstrap.blade.php
<style>
    body {
        background-color: #eee;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }

    .flex-container {
        padding: 20px;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -ms-flex-align: center;
        -webkit-align-items: center;
        -webkit-box-align: center;
        align-items: center;
    }

    .flex-container > * {
        margin: auto;
    }

    .box-lockscreen {
        min-width: 280px;
        max-width: 400px;
        height: auto;
        background-color: rgba(255, 255, 255, .9);
        border: 1px solid #d1d4d7;
        padding: 30px;
    }

    h2 {
        font-size: 16px;
        line-height: 16px;
        font-weight: 400;
    }

    p {
        margin-top: -8px;
        font-weight: 300;
    }

    .input-group {
        position: relative;
        display: flex;
        border-collapse: separate;
    }

    .input-group .form-control, .input-group-btn {
        display: table-cell;
    }

    .input-group .form-control {
        position: relative;
        z-index: 2;
        float: left;
        width: 100%;
        margin-bottom: 0;
        border: 1px solid #d1d4d7;
        color: #3d3f42;
    }

    .form-control {
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
        -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
    }

    .input-group-btn:last-child > .btn, .input-group-btn:last-child > .btn-group {
        margin-left: -1px;
    }

    .input-group-btn > .btn {
        position: relative;
        margin-bottom: 25px;
        color: #fff;
        background: #337ab7;
        border: 1px solid #337ab7;
        text-shadow: none;
    }

    .btn {
        display: inline-block;
        padding: 6px 12px;
        margin-bottom: 0;
        font-size: 14px;
        font-weight: 400;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        -ms-touch-action: manipulation;
        touch-action: manipulation;
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        background-image: none;
        border: 1px solid transparent;
    }

    a {
        display: block;
        font-weight: 300;
        font-size: 14px;
        color: #337ab7;
        text-decoration: none;
    }
</style>

src/resources/views/styles/bulma.blade.php
<style>
    body {
        background-color: #eee;
        font-family: 'Roboto', sans-serif;
    }

    .flex-container {
        padding: 20px;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -ms-flex-align: center;
        -webkit-align-items: center;
        -webkit-box-align: center;
        align-items: center;
    }

    .flex-container > * {
        margin: auto;
    }

    .box-lockscreen {
        min-width: 280px;
        max-width: 400px;
        height: auto;
        background-color: rgba(255, 255, 255, .9);
        border: 1px solid #d1d4d7;
        padding: 30px;
    }

    h2 {
        font-size: 16px;
        line-height: 16px;
        font-weight: 400;
        text-align: center;
    }

    p {
        margin-top: -8px;
        font-weight: 300;
        text-align: center;
    }

    .group {
        position: relative;
        margin-bottom: 10px;
        margin-top: 20px;
    }

    input {
        -moz-appearance: none;
        -webkit-appearance: none;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        border: 1px solid transparent;
        -webkit-border-radius: 290486px;
        -moz-border-radius: 290486px;
        border-radius: 290486px;
        -webkit-box-shadow: none;
        box-shadow: none;
        display: -webkit-inline-box;
        display: -ms-inline-flexbox;
        display: inline-flex;
        font-size: 1rem;
        height: 2.25em;
        -webkit-box-pack: start;
        -ms-flex-pack: start;
        justify-content: flex-start;
        line-height: 1.5;
        padding-bottom: calc(0.375em - 1px);
        padding-left: calc(0.625em + 5px);
        padding-right: calc(0.625em - 1px);
        padding-top: calc(0.375em - 1px);
        position: relative;
        vertical-align: top;
        background-color: white;
        border-color: #dbdbdb;
        color: #363636;
        -webkit-box-shadow: inset 0 1px 2px rgba(10, 10, 10, 0.1);
        box-shadow: inset 0 1px 2px rgba(10, 10, 10, 0.1);
        max-width: 100%;
        width: 100%;
    }

    input:focus {
        outline: none;
    }

    .btn {
        -moz-appearance: none;
        -webkit-appearance: none;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        border: 1px solid transparent;
        border-radius: 3px;
        -webkit-box-shadow: none;
        box-shadow: none;
        display: block;
        font-size: 1rem;
        height: 2.25em;
        -webkit-box-pack: start;
        -ms-flex-pack: start;
        justify-content: flex-start;
        line-height: 1.5;
        padding-bottom: calc(0.375em - 1px);
        padding-left: calc(0.625em - 1px);
        padding-right: calc(0.625em - 1px);
        padding-top: calc(0.375em - 1px);
        position: relative;
        vertical-align: top;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        background-color: white;
        border-color: #dbdbdb;
        color: #363636;
        cursor: pointer;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        padding-left: 0.75em;
        padding-right: 0.75em;
        text-align: center;
        white-space: nowrap;
        -webkit-border-radius: 290486px;
        -moz-border-radius: 290486px;
        border-radius: 290486px;
        padding-left: 3em;
        padding-right: 3em;
        margin: 0 auto;
    }

    .btn{
        background-color: #3273dc;
        border-color: transparent;
        color: #fff;
    }

    .btn:hover{
        background-color: #276cda;
        border-color: transparent;
        color: #fff;
    }

    .btn:focus, .btn:active {
        outline: none;
    }

    a {
        display: block;
        font-weight: 500;
        font-size: 14px;
        color: #337ab7;
        text-decoration: none;
        -webkit-tap-highlight-color: transparent;
        text-align: center;
    }
</style>

src/resources/views/styles/materialize.blade.php
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<style>
    body {
        background-color: #eee;
        font-family: 'Roboto', sans-serif;
    }

    .flex-container {
        padding: 20px;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -ms-flex-align: center;
        -webkit-align-items: center;
        -webkit-box-align: center;
        align-items: center;
    }

    .flex-container > * {
        margin: auto;
    }

    .box-lockscreen {
        min-width: 280px;
        max-width: 400px;
        height: auto;
        background-color: rgba(255, 255, 255, .9);
        border: 1px solid #d1d4d7;
        padding: 30px;
    }

    h2 {
        font-size: 16px;
        line-height: 16px;
        font-weight: 400;
    }

    p {
        margin-top: -8px;
        font-weight: 300;
    }

    .group {
        position: relative;
        margin-bottom: 10px;
        margin-top: 40px;
    }

    input {
        font-size: 18px;
        padding: 10px 10px 10px 0px;
        display: block;
        width: 300px;
        border: none;
        border-bottom: 1px solid #757575;
    }

    input:focus {
        outline: none;
    }

    /* LABEL ======================================= */
    label {
        color: #999;
        font-size: 16px;
        font-weight: normal;
        position: absolute;
        pointer-events: none;
        top: 15px;
        transition: 0.2s ease all;
        -moz-transition: 0.2s ease all;
        -webkit-transition: 0.2s ease all;
    }

    /* active state */
    input:focus ~ label, input:valid ~ label {
        top: -20px;
        font-size: 14px;
        color: #5264AE;
    }

    /* BOTTOM BARS ================================= */
    .bar {
        position: relative;
        display: block;
        width: 300px;
    }

    .bar:before, .bar:after {
        content: '';
        height: 2px;
        width: 0;
        bottom: 1px;
        position: absolute;
        background: #5264AE;
        transition: 0.2s ease all;
        -moz-transition: 0.2s ease all;
        -webkit-transition: 0.2s ease all;
    }

    .bar:before {
        left: 50%;
    }

    .bar:after {
        right: 50%;
    }

    /* active state */
    input:focus ~ .bar:before, input:focus ~ .bar:after {
        width: 50%;
    }

    /* active state */
    input:focus ~ .highlight {
        -webkit-animation: inputHighlighter 0.3s ease;
        -moz-animation: inputHighlighter 0.3s ease;
        animation: inputHighlighter 0.3s ease;
    }

    /* ANIMATIONS ================ */
    @-webkit-keyframes inputHighlighter {
        from {
            background: #5264AE;
        }
        to {
            width: 0;
            background: transparent;
        }
    }

    @-moz-keyframes inputHighlighter {
        from {
            background: #5264AE;
        }
        to {
            width: 0;
            background: transparent;
        }
    }

    @keyframes inputHighlighter {
        from {
            background: #5264AE;
        }
        to {
            width: 0;
            background: transparent;
        }
    }

    .btn {
        text-decoration: none;
        color: #fff;
        background-color: #5264AE;
        text-align: center;
        letter-spacing: .5px;
        -webkit-transition: 0.2s ease-out;
        -moz-transition: 0.2s ease-out;
        -o-transition: 0.2s ease-out;
        -ms-transition: 0.2s ease-out;
        transition: 0.2s ease-out;
        cursor: pointer;
        border: none;
        border-radius: 2px;
        height: 36px;
        line-height: 36px;
        outline: 0;
        padding: 0 2rem;
        text-transform: uppercase;
        vertical-align: middle;
        -webkit-tap-highlight-color: transparent;
        display: block;
        position: relative;
        overflow: hidden;
    }

    .btn:after {
        content: '';
        position: absolute;
        top: 50%;
        left: 50%;
        width: 5px;
        height: 5px;
        background: rgba(255, 255, 255, .5);
        opacity: 0;
        border-radius: 100%;
        transform: scale(1, 1) translate(-50%);
        transform-origin: 50% 50%;
    }

    .btn:focus:not(:active)::after {
        animation: ripple 1s ease-out;
    }

    a {
        display: block;
        font-weight: 500;
        font-size: 14px;
        color: #337ab7;
        text-decoration: none;
        -webkit-tap-highlight-color: transparent;
    }

    @keyframes ripple {
        0% {
            transform: scale(0, 0);
            opacity: 1;
        }
        20% {
            transform: scale(25, 25);
            opacity: 1;
        }
        100% {
            opacity: 0;
            transform: scale(40, 40);
        }
    }
</style>

src/resources/views/themes/adminlte.blade.php
<div class="box-lockscreen">
    <h2><strong>{{ Auth::user()->name }}</strong></h2>
    <p>{{ Auth::user()->email }}</p>

    <form action="{{ route('lockscreen.unlock') }}" method="POST">
        {{ csrf_field() }}

        <div class="input-group">
            <input class="form-control" type="password" name="password" placeholder="Password" required>
            <span class="input-group-btn">
                <button class="btn">Unlock</button>
            </span>
        </div>
    </form>

    <a href="javascript:void(0)" id="lockscreen-logout">I'm not {{ Auth::user()->name }}</a>
</div>

src/resources/views/themes/bootstrap.blade.php
<div class="box-lockscreen">
    <h2><strong>{{ Auth::user()->name }}</strong></h2>
    <p>{{ Auth::user()->email }}</p>

    <form action="{{ route('lockscreen.unlock') }}" method="POST">
        {{ csrf_field() }}

        <div class="input-group">
            <input class="form-control" type="password" name="password" placeholder="Password" required>
            <span class="input-group-btn">
                <button class="btn">Unlock</button>
            </span>
        </div>
    </form>

    <a href="javascript:void(0)" id="lockscreen-logout">I'm not {{ Auth::user()->name }}</a>
</div>

src/resources/views/themes/bulma.blade.php
<div class="box-lockscreen">
    <h2><strong>{{ Auth::user()->name }}</strong></h2>
    <p>{{ Auth::user()->email }}</p>

    <form action="{{ route('lockscreen.unlock') }}" method="POST">
        {{ csrf_field() }}

        <div class="group">
            <input type="password" name="password" placeholder="Password" required>
        </div>

        <button class="btn">Unlock</button>
    </form>

    <a href="javascript:void(0)" id="lockscreen-logout">I'm not {{ Auth::user()->name }}</a>
</div>

src/resources/views/themes/materialize.blade.php
<div class="box-lockscreen">
    <h2><strong>{{ Auth::user()->name }}</strong></h2>
    <p>{{ Auth::user()->email }}</p>

    <form action="{{ route('lockscreen.unlock') }}" method="POST">
        {{ csrf_field() }}

        <div class="group">
            <input type="password" name="password" required>
            <span class="bar"></span>
            <label>Password</label>
        </div>

        <button class="btn">Unlock</button>
    </form>

    <a href="javascript:void(0)" id="lockscreen-logout">I'm not {{ Auth::user()->name }}</a>
</div>